# config.yaml
# --- General run settings ---
run_settings:
  device: 'cuda'  # 'cuda' or 'cpu'

# --- Pruning parameters ---
pruning:
  layer_name: 'features.2'  # The specific layer you want to prune
  threshold: 0.0          # Threshold for negative_impact_pruning

# --- File paths ---
paths:
  # Directory for saving weight files
  weights_dir: 'Weights'
  # Directory for saving ranking arrays
  rankings_dir: 'Ranking_arrays'
  
  # Specific file names
  greedy_pruned_model: 'pruned_model.pth'
  negative_pruned_model: 'negative_impact_pruned_model.pth'
  importance_scores: 'real_authenticity_batch_importance_scores.npy'

# --- Model/Data settings (example) ---
data:
  batch_size: 16
  # ... other data params